// CREATE ACCOUNT
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "name": "Muhammad Adam",
  "email": "adam@gmail.com",
  "password": "123",
  "confPassword": "123"
}


###
// GET ALL USER
GET http://localhost:5000/users


###
// GET SINGLE USER
GET http://localhost:5000/users/a03b1620-c306-41f3-9b19-3bf106d1a543


###
// UPDATE USER
PATCH http://localhost:5000/update/cb02d4c4-7b15-48b4-85e3-83cde7e20b93
Content-Type: application/json

{
  "name": "Faishal Yusuf",
  "email": "faishal@gmail.com",
  "password": "",
  "confPassword": ""
}


###
// DELETE USER
DELETE http://localhost:5000/delete/0687a6cd-5f09-4e97-8d11-feb098466a93


###
// LOGIN ADMIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "faishal@gmail.com",
  "password": "123"
}
###
// LOGIN USER
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "harits@gmail.com",
  "password": "123"
}


###
// VERIFY WHO IS INSIDE
GET http://localhost:5000/me


###
// LOGOUT USER
DELETE http://localhost:5000/Logout



















###
// GET ALL STORIES
GET http://localhost:5000/stories



###
// CREATE STORIES
POST http://localhost:5000/stories/create
Content-Type: application/json

{
  "description": "file kedua"
}


###
/// GET SINGLE STORIES
GET http://localhost:5000/stories/f8eb728d-892f-46b9-9fd9-70f65bf1d7a2



###
// EDIT STORIES
PATCH http://localhost:5000/stories/edit/f8eb728d-892f-46b9-9fd9-70f65bf1d7a2
Content-Type: application/json

{
  "description": "file kedua updated coy"
}



###
// DELETE STORIES
DELETE http://localhost:5000/stories/delete/89b4f305-162c-4cce-9dd3-92769c630857

