// CREATE ACCOUNT
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Faishal",
  "email": "email@gmail.com",
  "password": "123",
  "confPassword": "123",
  "role": "admin"
}


###
// GET ALL USER
GET http://localhost:5000/users


###
// GET SINGLE USER
GET http://localhost:5000/users/06a2660f-fc65-4ed1-b6d3-3fa475f0854a


###
// UPDATE USER
PATCH http://localhost:5000/users/1d4b9aeb-faf1-47ce-8062-d2e8d6776a95
Content-Type: application/json

{
  "name": "Faishal Yusuf Baqir",
  "email": "faishalyb@gmail.com",
  "password": "",
  "confPassword": "",
  "role": "admin"
}


###
// DELETE USER
DELETE http://localhost:5000/users/06a2660f-fc65-4ed1-b6d3-3fa475f0854a


###
// LOGIN USER
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "123"
}


###
// VERIFY WHO IS INSIDE
GET http://localhost:5000/me


###
// LOGOUT USER
DELETE http://localhost:5000/Logout
