// CREATE ACCOUNT
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Faishal",
  "email": "email@gmail.com",
  "password": "123",
  "confPassword": "123",
  "role": "admin"
}


###
// GET ALL USER
GET http://localhost:5000/users


// GET SINGLE USER

